/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package time.vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Edwin
 */
public class Setting extends javax.swing.JDialog {

    /**
     * Creates new form Setting
     */
  
    public Setting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Image/clock.png")).getImage());
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jCBFont = new javax.swing.JComboBox<>();
        jCBFontStyle = new javax.swing.JComboBox<>();
        jCBSize = new javax.swing.JComboBox<>();
        BtnSavaChange = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        rb_opcio1 = new javax.swing.JRadioButton();
        rb_opcio2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(860, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBFont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial ", "Arial Black", "Arial Narrow", "Bahnschrift", "Barlow Condensed", "Barlow Condensed Black", "Barlow Condensed Light", "Barlow Condensed Medium", "Cambria", "Candara", "Castellar", "Centaur", "Consolas", "Roboto", "Roboto Black", "Roboto Light", "Segoe UI", "Segoe UI Black", "Montserrat", "Montserrat Black" }));
        jPanel1.add(jCBFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 120, -1));

        jCBFontStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plain", "Bold", "Italic", "Bold Italic", " " }));
        jPanel1.add(jCBFontStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, -1));

        jCBSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "35", "37", "39", "41", "43", "45", "46", "48", "50", "52", "53", "55", "56", "57", "60", "62", "63", "65", "66", "67", "70", "72", "73", "75", " ", " ", " ", " ", " " }));
        jPanel1.add(jCBSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 70, -1));

        BtnSavaChange.setBackground(new java.awt.Color(255, 255, 255));
        BtnSavaChange.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        BtnSavaChange.setForeground(new java.awt.Color(255, 255, 255));
        BtnSavaChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Buttom.png"))); // NOI18N
        BtnSavaChange.setBorder(null);
        BtnSavaChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSavaChangeActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSavaChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 140, 60));

        jSeparator1.setForeground(new java.awt.Color(234, 232, 232));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 280, 30));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Font Style");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 230, 50));

        rb_opcio1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_opcio1);
        jPanel1.add(rb_opcio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        rb_opcio2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb_opcio2);
        jPanel1.add(rb_opcio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 255, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/capa1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 600, 190));

        jSeparator2.setForeground(new java.awt.Color(234, 232, 232));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 250, 30));

        jSeparator3.setForeground(new java.awt.Color(234, 232, 232));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 280, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apparence 2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 320, 130));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/apparence 1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 320, 130));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Appearance");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSavaChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSavaChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSavaChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnSavaChange;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> jCBFont;
    public javax.swing.JComboBox<String> jCBFontStyle;
    public javax.swing.JComboBox<String> jCBSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JRadioButton rb_opcio1;
    public javax.swing.JRadioButton rb_opcio2;
    // End of variables declaration//GEN-END:variables
}
